import { immediateBeforeId } from "@src/redis/RedisStreamIdHelper";

describe("RedisStreamIdHelper", () => {
  describe("immediateBeforeId", () => {
    it.each([
      { id: "1111-0", immediateBefore: "1110-999" },
      { id: "1-1", immediateBefore: "1-0" },
      { id: "123456-9", immediateBefore: "123456-8" },
    ])(
      "should return calculate and return immediate before id, respecting Redis Stream autogenerated id format - id: $id | immediateBefore: $immediateBefore",
      (testCaseParameters) => {
        expect(immediateBeforeId(testCaseParameters.id)).toBe(testCaseParameters.immediateBefore);
      }
    );
  });
});
